// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Schema changes (db push / migrate) run over Supabase's direct connection.
    // The pooled DATABASE_URL is for the app runtime (Prisma Client) instead.
    url: process.env["DIRECT_URL"],
  },
});
